# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.DateTimeField(verbose_name='edad')),
                ('color', models.CharField(max_length=50)),
                ('peso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.DateTimeField(verbose_name='edad')),
                ('color', models.CharField(max_length=50)),
                ('peso', models.IntegerField(default=0)),
            ],
        ),
    ]
