# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
