# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0005_auto_20171007_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='edad',
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha_publicacion'),
            preserve_default=False,
        ),
    ]
