# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_auto_20171007_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.Mascota')),
            ],
        ),
    ]
