# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0008_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.Animal'),
        ),
    ]
