# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0011_auto_20171007_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='buscador/static/buscador/pics')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buscador.Animal')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
