# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0012_auto_20171007_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='animal',
        ),
    ]
